module.exports = [
	{
		name: "openrouter",
		apiKey: [
			process.env.OPENROUTER_API_KEY,
			process.env.OPENROUTER_API_KEY_2,
			process.env.OPENROUTER_API_KEY_3,
			process.env.OPENROUTER_API_KEY_4,
			process.env.OPENROUTER_API_KEY_5,
			process.env.OPENROUTER_API_KEY_6,
			process.env.OPENROUTER_API_KEY_7,
			process.env.OPENROUTER_API_KEY_8,
			process.env.OPENROUTER_API_KEY_9,
			process.env.OPENROUTER_API_KEY_10,
			process.env.OPENROUTER_API_KEY_11,
			process.env.OPENROUTER_API_KEY_12,
			process.env.OPENROUTER_API_KEY_13,
			process.env.OPENROUTER_API_KEY_14,
			process.env.OPENROUTER_API_KEY_15,
			process.env.OPENROUTER_API_KEY_16,
			process.env.OPENROUTER_API_KEY_17,
			process.env.OPENROUTER_API_KEY_18,
			process.env.OPENROUTER_API_KEY_19,
			process.env.OPENROUTER_API_KEY_20,
			process.env.OPENROUTER_API_KEY_21,
			process.env.OPENROUTER_API_KEY_22,
			process.env.OPENROUTER_API_KEY_23,
			process.env.OPENROUTER_API_KEY_24,
			process.env.OPENROUTER_API_KEY_25,
			process.env.OPENROUTER_API_KEY_26,
			process.env.OPENROUTER_API_KEY_27,
			process.env.OPENROUTER_API_KEY_28,
			process.env.OPENROUTER_API_KEY_29,
			process.env.OPENROUTER_API_KEY_30,
			process.env.OPENROUTER_API_KEY_31,
			process.env.OPENROUTER_API_KEY_32,
			process.env.OPENROUTER_API_KEY_33,
			process.env.OPENROUTER_API_KEY_34,
			process.env.OPENROUTER_API_KEY_35,
			process.env.OPENROUTER_API_KEY_36,
			process.env.OPENROUTER_API_KEY_37,
			process.env.OPENROUTER_API_KEY_38,
			process.env.OPENROUTER_API_KEY_39,
			process.env.OPENROUTER_API_KEY_40,
			process.env.OPENROUTER_API_KEY_41,
			process.env.OPENROUTER_API_KEY_42,
			process.env.OPENROUTER_API_KEY_43,
			process.env.OPENROUTER_API_KEY_44,
			process.env.OPENROUTER_API_KEY_45,
			process.env.OPENROUTER_API_KEY_46,
			process.env.OPENROUTER_API_KEY_47,
			process.env.OPENROUTER_API_KEY_48,
			process.env.OPENROUTER_API_KEY_49,
			process.env.OPENROUTER_API_KEY_50,
			process.env.OPENROUTER_API_KEY_51,
			process.env.OPENROUTER_API_KEY_52,
			process.env.OPENROUTER_API_KEY_53
		],
		model: [
			"openrouter/aurora-alpha",
			"openai/gpt-oss-120b:free",
			"qwen/qwen3-coder:free",
			"arcee-ai/trinity-large-preview:free",
		],
		apiUrl: "https://openrouter.ai/api/v1",
	},
	{
		name: "gemini",
		apiKey: [
			process.env.GEMINI_API_KEY_1,
		],
		model: [
			"gemini-3-pro-preview",
			"gemini-3-flash-preview",
			"gemini-2.5-flash"
		],
		apiUrl: "https://generativelanguage.googleapis.com/v1beta/openai/",
	},
	{
		name: "cerebras",
		apiKey: [
			process.env.CEREBRAS_API_KEY_1,
			process.env.CEREBRAS_API_KEY_2
		],
		model: [
			"gpt-oss-120b",
			"qwen-3-235b-a22b-instruct-2507",
			"zai-glm-4.7"
		],
		apiUrl: "https://api.cerebras.ai/v1",
	},
];